language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1.4
    - os: osx
      osx_image: xcode9
      mono: none
      dotnet: 2.1.4

before_script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-get install liblmdb-dev; fi

script:
  - dotnet --info
  - ./build.sh
